<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SlotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $insert = [
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],  
            
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],  
            
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            

            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],  
            
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],  
            
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], 
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]

        ];        
        DB::table('slots')->insert($insert);
    }
}
