<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SlotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $insert = [
            [
                'slot_name' => 'Hall 1 : Polident Hall - 203',
                'slot_time' => '9:30am to 11:30am',
                'slot_price_first_step' => '2000',
                'slot_price' => '6000',
                'slot_date' => '2024-02-03',
                'speaker' => 'DR FILIPPO CARDINALI <br> DR GERASIMOS GIANNAKIS',
                'description' => 'Learning Tips for Successful Obturation - META',
                'slot_seats' => '5',
                'workshop' => '1',  //incrementing number
                'topic_desc' => 'Gain an overview of the rubber dam’s significance in contemporary dentistry, highlighting its applications, benefits, and potential considerations y doing hands-on with anterior quadrant isolation.',
                'type' => 'Advanced',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall 1 : Polident Hall - 203',
                'slot_time' => '11:45am to 1:45pm',
                'slot_price_first_step' => '5000',
                'slot_price' => '8000',
                'slot_date' => '2024-02-03',
                'speaker' => 'DR JAYSHREE HEGDE',
                'description' => 'Embracing Challenging Canal Anatomy: Formula for Success - COLTENE',
                'slot_seats' => '5',
                'workshop' => '2', //incrementing number
                'topic_desc' => 'How, in just one hour, to build up a tooth from zero and mastering the finishing & polishing in only 3 steps.',
                'type' => 'Premium',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-04'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],



            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '08am to 10am',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '11am to 01pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '02pm to 04pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'slot_name' => 'Hall A (Suite 202)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '1000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall B (Suite 203)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '2000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall C (Suite 204A)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '3000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'slot_name' => 'Hall D (Suite 204B)',
                'slot_time' => '05am to 07pm',
                'speaker' => 'Amit',
                'description' => 'Topic name here',
                'slot_date' => date('2023-02-05'),
                'slot_seats' => '15',
                'slot_price' => '4000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]

        ];
        DB::table('slots')->insert($insert);
    }
}
